using SimpleERP.Application.DTOs;
using SimpleERP.Application.Interfaces;
using SimpleERP.Domain.Entities;
using SimpleERP.Domain.Enums;
using SimpleERP.Domain.Interfaces;

namespace SimpleERP.Application.Services;

/// <summary>
/// Credit and debit notes as standalone documents.
///
/// Returns raise their own notes inside the return transaction (see ReturnService) — this
/// service is for the notes with no goods behind them: a price dispute, a billing error,
/// a rebate settled by credit against the payable. That standalone case was an explicit
/// gap in the original design, where a note could only ever come from a return.
///
/// A note raised here moves money and nothing else. Notes generated by a return are
/// deliberately not cancellable from here: cancelling one has to reverse the stock too,
/// which only the return knows how to do.
/// </summary>
public class CreditNoteService : ICreditNoteService
{
    private readonly ICreditNoteRepository  _notes;
    private readonly ICustomerRepository    _customers;
    private readonly ISupplierRepository    _suppliers;
    private readonly ISaleRepository        _sales;
    private readonly IPurchaseRepository    _purchases;
    private readonly IAppSettingsRepository _settings;
    private readonly IAuditLogRepository    _audit;
    private readonly IUnitOfWork            _uow;

    public CreditNoteService(ICreditNoteRepository notes, ICustomerRepository customers,
        ISupplierRepository suppliers, ISaleRepository sales, IPurchaseRepository purchases,
        IAppSettingsRepository settings, IAuditLogRepository audit, IUnitOfWork uow)
    { _notes=notes; _customers=customers; _suppliers=suppliers; _sales=sales;
      _purchases=purchases; _settings=settings; _audit=audit; _uow=uow; }

    public async Task<List<CreditNoteDto>> GetAllAsync(CreditDebitType? type = null,
        CreditNoteStatus? status = null, DateTime? from = null, DateTime? to = null)
        => (await _notes.GetAllAsync(type, status, from, to)).Select(MapDto).ToList();

    public async Task<CreditNoteDto?> GetByIdAsync(Guid id)
    {
        var note = await _notes.GetByIdAsync(id);
        return note == null ? null : MapDto(note);
    }

    public Task<decimal> GetOpenTotalAsync(CreditDebitType type) => _notes.GetOpenTotalAsync(type);

    public async Task<ServiceResult> CreateAsync(CreateCreditNoteDto dto, string user)
    {
        var reason = Trim(dto.Reason, 500);
        if (reason == null)  return ServiceResult.Fail("A reason for the note is required.");
        if (dto.Amount <= 0) return ServiceResult.Fail("Amount must be greater than zero.");

        var noteDate = dto.NoteDate?.Date ?? DateTime.UtcNow.Date;
        if (noteDate > DateTime.UtcNow.Date.AddDays(1))
            return ServiceResult.Fail("Note date cannot be in the future.");

        var isCredit = dto.Type == CreditDebitType.Credit;

        // Exactly one counterparty, matching the direction — a credit note is owed to a
        // customer, a debit note is owed by a supplier.
        Guid? customerId = null, supplierId = null;
        if (isCredit)
        {
            if (dto.CustomerId == null || dto.CustomerId == Guid.Empty)
                return ServiceResult.Fail("A credit note needs a customer.");
            if (await _customers.GetByIdAsync(dto.CustomerId.Value) == null)
                return ServiceResult.Fail("Customer not found.");
            customerId = dto.CustomerId;
        }
        else
        {
            if (dto.SupplierId == null || dto.SupplierId == Guid.Empty)
                return ServiceResult.Fail("A debit note needs a supplier.");
            if (await _suppliers.GetByIdAsync(dto.SupplierId.Value) == null)
                return ServiceResult.Fail("Supplier not found.");
            supplierId = dto.SupplierId;
        }

        // A linked source document supplies the tax rate, so the adjustment reverses the
        // rate that was actually charged rather than today's setting. It also has to
        // belong to the same counterparty, or the note would net off the wrong balance.
        decimal taxRate;
        Guid?   sourceSaleId = null, sourcePurchaseId = null;

        if (isCredit && dto.SourceSaleId.HasValue)
        {
            var sale = await _sales.GetByIdWithItemsAsync(dto.SourceSaleId.Value);
            if (sale == null) return ServiceResult.Fail("Linked invoice not found.");
            if (sale.CustomerId != customerId)
                return ServiceResult.Fail(
                    $"Invoice {sale.InvoiceNumber} belongs to a different customer.");
            taxRate      = sale.TaxRate;
            sourceSaleId = sale.Id;
        }
        else if (!isCredit && dto.SourcePurchaseId.HasValue)
        {
            var purchase = await _purchases.GetByIdWithItemsAsync(dto.SourcePurchaseId.Value);
            if (purchase == null) return ServiceResult.Fail("Linked purchase not found.");
            if (purchase.SupplierId != supplierId)
                return ServiceResult.Fail(
                    $"Purchase {purchase.PurchaseNumber} belongs to a different supplier.");
            taxRate          = purchase.TaxRate;
            sourcePurchaseId = purchase.Id;
        }
        else
        {
            taxRate = (await _settings.GetAsync()).VatRate;
        }

        var (taxBase, taxAmount, total) = MoneyMath.SplitTax(dto.Amount, taxRate, dto.IsTaxInclusive);

        var note = new CreditNote {
            Id               = Guid.NewGuid(),
            DocumentNumber   = await _notes.GenerateDocumentNumberAsync(dto.Type),
            Type             = dto.Type,
            Category         = dto.Category,
            NoteDate         = noteDate,
            CustomerId       = customerId,
            SupplierId       = supplierId,
            TaxBase          = taxBase,
            TaxRate          = taxRate,
            TaxAmount        = taxAmount,
            Amount           = total,
            SourceSaleId     = sourceSaleId,
            SourcePurchaseId = sourcePurchaseId,
            Status           = CreditNoteStatus.Open,
            Reason           = reason,
            Notes            = Trim(dto.Notes, 500),
            CreatedBy        = user,
            CreatedAt        = DateTime.UtcNow
        };

        await _notes.AddAsync(note);
        await _audit.LogAsync(user, $"{dto.Type}Note.Create",
            $"{note.DocumentNumber} | {note.Category} | {total:N0}");
        await _uow.SaveChangesAsync();
        return ServiceResult.Ok();
    }

    public async Task<ServiceResult> SettleAsync(SettleCreditNoteDto dto, string user)
    {
        var note = await _notes.GetByIdAsync(dto.Id);
        if (note == null) return ServiceResult.Fail("Note not found.");
        if (note.Status == CreditNoteStatus.Settled)
            return ServiceResult.Fail($"{note.DocumentNumber} is already settled.");
        if (note.Status == CreditNoteStatus.Cancelled)
            return ServiceResult.Fail($"{note.DocumentNumber} is cancelled.");

        note.Status          = CreditNoteStatus.Settled;
        note.SettledDate     = DateTime.UtcNow;
        note.SettlementNotes = Trim(dto.SettlementNotes, 500);
        _notes.Update(note);

        await _audit.LogAsync(user, $"{note.Type}Note.Settle",
            $"{note.DocumentNumber} | {note.Amount:N0}" +
            (note.SettlementNotes != null ? $" | {note.SettlementNotes}" : ""));
        await _uow.SaveChangesAsync();
        return ServiceResult.Ok();
    }

    public async Task<ServiceResult> CancelAsync(Guid id, string user)
    {
        var note = await _notes.GetByIdAsync(id);
        if (note == null) return ServiceResult.Fail("Note not found.");
        if (note.Status == CreditNoteStatus.Cancelled)
            return ServiceResult.Fail($"{note.DocumentNumber} is already cancelled.");
        if (note.Status == CreditNoteStatus.Settled)
            return ServiceResult.Fail(
                $"{note.DocumentNumber} has already been settled — the money has moved. " +
                "Raise an opposite note instead of cancelling this one.");

        // A return's note can't be cancelled on its own: the goods movement has to be
        // reversed with it, and only the return knows how.
        if (note.SourceCustomerReturnId.HasValue || note.SourceSupplierReturnId.HasValue)
        {
            var returnNumber = note.SourceCustomerReturn?.ReturnNumber
                            ?? note.SourceSupplierReturn?.ReturnNumber ?? "the return";
            return ServiceResult.Fail(
                $"{note.DocumentNumber} was raised by return {returnNumber}. Cancel that " +
                "return instead — it reverses the stock movement as well as this note.");
        }

        note.Status = CreditNoteStatus.Cancelled;
        _notes.Update(note);

        await _audit.LogAsync(user, $"{note.Type}Note.Cancel", note.DocumentNumber);
        await _uow.SaveChangesAsync();
        return ServiceResult.Ok();
    }

    private static string? Trim(string? s, int max)
        => string.IsNullOrWhiteSpace(s) ? null : (s.Trim().Length > max ? s.Trim()[..max] : s.Trim());

    private static CreditNoteDto MapDto(CreditNote n) => new() {
        Id               = n.Id,
        DocumentNumber   = n.DocumentNumber,
        Type             = n.Type.ToString(),
        IsCredit         = n.Type == CreditDebitType.Credit,
        Category         = n.Category.ToString(),
        NoteDate         = n.NoteDate,
        CounterpartyName = n.Customer?.Name ?? n.Supplier?.Name ?? "",
        TaxBase          = n.TaxBase,
        TaxRate          = n.TaxRate,
        TaxAmount        = n.TaxAmount,
        Amount           = n.Amount,
        // Prefer the return that raised it — that's the document staff would go back to.
        SourceDocument   = n.SourceCustomerReturn?.ReturnNumber
                        ?? n.SourceSupplierReturn?.ReturnNumber
                        ?? n.SourceSale?.InvoiceNumber
                        ?? n.SourcePurchase?.PurchaseNumber ?? "",
        SourceSaleId           = n.SourceSaleId,
        SourcePurchaseId       = n.SourcePurchaseId,
        SourceCustomerReturnId = n.SourceCustomerReturnId,
        SourceSupplierReturnId = n.SourceSupplierReturnId,
        Status           = n.Status.ToString(),
        IsOpen           = n.Status == CreditNoteStatus.Open,
        SettledDate      = n.SettledDate,
        SettlementNotes  = n.SettlementNotes,
        Reason           = n.Reason,
        Notes            = n.Notes,
        CreatedBy        = n.CreatedBy
    };
}
