using SimpleERP.Domain.Enums;

namespace SimpleERP.Domain.Entities;

/// <summary>
/// One supplier invoice, received as a single multi-line document — the mirror image
/// of Sale, not the one-product-at-a-time Stock In page. Stock for every line is
/// received when the document is posted, in one transaction.
/// </summary>
public class Purchase
{
    public Guid        Id             { get; set; }
    /// <summary>
    /// Our own generated document number (PO-yyyyMM-nnnn), unique. Exists because we
    /// need a stable internal handle that doesn't depend on a supplier's numbering.
    /// </summary>
    public string      PurchaseNumber { get; set; } = string.Empty;
    /// <summary>
    /// The supplier's own invoice/PO number, exactly as printed on their paperwork.
    /// Not unique and not generated by us — two suppliers can and do reuse the same
    /// number. Captured because the rebate reconciliation sheet keys settlements to a
    /// specific supplier invoice: without it there is nothing firm to match a
    /// RebateAccrual back to the paper document it came from.
    /// </summary>
    public string?     SupplierDocumentNumber { get; set; }
    public DateTime    PurchaseDate   { get; set; } = DateTime.UtcNow;
    public Guid        SupplierId     { get; set; }
    public Guid        BranchId       { get; set; }
    public PaymentType PaymentType    { get; set; }
    /// <summary>Credit term for this purchase. Null for Cash and for open credit.</summary>
    public Guid?       PaymentTermId  { get; set; }
    /// <summary>When we owe the supplier. PurchaseDate + PaymentTerm.DueDays.</summary>
    public DateTime?   DueDate        { get; set; }
    public decimal     SubTotal       { get; set; }
    /// <summary>Sum of line-level discounts only. Document-level sits separately below.</summary>
    public decimal     DiscountTotal  { get; set; }
    /// <summary>
    /// Whole-document discount as granted by the supplier. Allocated pro-rata onto
    /// PurchaseItem.AllocatedInvoiceDiscount for the same reason the sales side does
    /// it: the rebate engine computes real cost per line
    /// (UnitCost − RebateAccrual.Amount / Qty), and a header-only discount would
    /// silently overstate the cost of every line it touched.
    /// </summary>
    public decimal     InvoiceDiscountAmount  { get; set; }
    /// <summary>Percent as entered, when given that way. Null = flat amount. Never used for arithmetic.</summary>
    public decimal?    InvoiceDiscountPercent { get; set; }
    /// <summary>PPN Masukan taxable base (DPP) for this purchase.</summary>
    public decimal     TaxBase        { get; set; }
    /// <summary>PPN rate applied, as a fraction (0.10 = 10%). Snapshotted at posting time.</summary>
    public decimal     TaxRate        { get; set; }
    public decimal     TaxAmount      { get; set; }
    /// <summary>True if the supplier's quoted costs already included PPN.</summary>
    public bool        IsTaxInclusive { get; set; }
    public decimal     GrandTotal     { get; set; }
    /// <summary>How much we have paid the supplier so far.</summary>
    public decimal     AmountPaid     { get; set; }
    public PurchaseStatus Status      { get; set; } = PurchaseStatus.Active;
    public string?     Notes          { get; set; }
    public string      CreatedBy      { get; set; } = "staff";
    public DateTime    CreatedAt      { get; set; } = DateTime.UtcNow;

    public Supplier?                    Supplier         { get; set; }
    public Branch?                      Branch           { get; set; }
    public PaymentTerm?                 PaymentTerm      { get; set; }
    public ICollection<PurchaseItem>    PurchaseItems    { get; set; } = new List<PurchaseItem>();
    public ICollection<SupplierPayment> SupplierPayments { get; set; } = new List<SupplierPayment>();
}
